# Generated by Django 3.0.2 on 2020-01-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback_new_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback_new',
            options={'ordering': ('-created_at',)},
        ),
    ]
