# Generated by Django 3.0.2 on 2020-01-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200121_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumOfParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_num', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='statistic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.NumOfParticipant'),
        ),
    ]
