# Generated by Django 3.0.2 on 2020-01-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200122_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='numofparticipant',
            name='description_num',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
