# Generated by Django 3.0.2 on 2020-01-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_numofparticipant_description_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='statistic',
            new_name='statistic_s',
        ),
    ]
